use_default_settings:
  engines:
    remove:
      - wikidata
      - ahmia
      - torch

server:
  secret_key: "change-me-to-random-string-abc123xyz"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""

ui:
  static_use_hash: true
